### PR TITLE
Update package.json to point at npm leaflet.graticule

### PR DESCRIPTION
**Pull request by jywarren**

### CODE REVIEW

**Comment by jywarren** [comment]
No! I don't 🤨

**Comment by mridulnagpal** [comment]
@jywarren It has something to do with phantomjs build, probably its not installing it on travis. Can we install phantomjs explicitly on travis?

**Comment by jywarren** [comment]
but it must be new... all previous builds worked fine! Ugh...

**Comment by jywarren** [comment]
Hmm, seeing `Fatal error: spawn /usr/bin/phantomjs ENOENT`...

**Comment by jywarren** [comment]
Whew! Finally!

**Pull request merged**
