### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jywarren**
I removed addGrid since that's in the setup stage, and replaced it with `setBlurred()` which is a critical part of the API. Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Merge if this looks good!

**Comment by mridulnagpal** [comment]
Made the changes for getPlacenameFromCoordinates() as well. Please have a look. #49

**Comment by jywarren** [comment]
Can you make `Used to get the location` be `Used to get the human-readable location name in text`? Then, looks good to merge!

**Comment by mridulnagpal** [comment]
Done! Merging now, cheers!

**Pull request merged**
