### PR TITLE
setCellSize method added to zoom handler and corresponding test spec added

### PR DESCRIPTION
**Pull request by mridulnagpal**

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren Please have a look, integrated the method to zoom handler, now cellSize changes each time you zoom in/out according to precision and degrees.

**Comment by jywarren** [comment]
Here's also a reference for implementing this type of grid, which i guess is called a Graticule: https://github.com/turban/Leaflet.Graticule

**Comment by mridulnagpal** [comment]
basically what we are trying to do is first find the precision, degrees then give each cell 1,0.1,0.01 degrees, whichever was returned from our function, right?

**Comment by jywarren** [comment]
Wow cool - this is good for comparison, to be sure it's running correctly: https://leaflet.github.io/Leaflet.Graticule/example/

In theory we could integrate this code in -- it doesn't have the highlighting, but could be a way to implement this with less of our own code. 

Yes, that's right!

**Comment by mridulnagpal** [comment]
Thats what I implemented please have a look, also this closes #17

**Comment by jywarren** [comment]
It looks like it's not quite there -- i think because we have to do latitude and longitude separately? 

See:

screenshot 2017-06-19 at 6 37 42 pm

**Comment by mridulnagpal** [comment]
I'll have a go at it.

**Comment by jywarren** [comment]
Maybe the code on `VirtualGrid` in the current implementation could be replaced by:

```
    L.latlngGraticule({
        showLabel: true,
        zoomInterval: [
            {start: 2, end: 3, interval: 30},
            {start: 4, end: 4, interval: 10},
            {start: 5, end: 7, interval: 5},
            {start: 8, end: 10, interval: 1}
        ]
    }).addTo(map);
```

And then we wouldn't have to set the grid size at all - we'd just have to figure out what grid square the center marker falls inside of... 

This is a bit different of an approach. Is it worth just merging this PR and doing this as a separate step?

**Comment by mridulnagpal** [comment]
Made changes please review

**Comment by mridulnagpal** [comment]
@jywarren Now the latitudes and longitudes have been separated so it appears in form of rectangles now instead of squares

**Comment by mridulnagpal** [comment]
also closes #21

**Comment by jywarren** [comment]
Cool, can you upload a pic of the same area around Chicago so we can
compare?

**Comment by mridulnagpal** [comment]
Can you send the co-ordinates

**Comment by mridulnagpal** [comment]
screenshot from 2017-06-20 05-27-21

**Comment by mridulnagpal** [comment]
@jywarren Almost the same I guess

**Comment by jywarren** [comment]
Looks perfect!!!!

**Comment by mridulnagpal** [comment]
Ready to merge, is it? Also have a look at the truncate lat lon functions.

**Comment by jywarren** [comment]
It looks great but isn't degrees of 100 precision -2? It's late and I'm tired so maybe I have this wrong but it's 2 places past zero right?

**Comment by mridulnagpal** [comment]
My bad coming right away

**Comment by mridulnagpal** [comment]
@jywarren Done

**Comment by jywarren** [comment]
Awesome!

**Comment by jywarren** [comment]
Hmm, something still seems wrong-- when you zoom in and out, the boxes move around -- do you know why? We should open a new issue for this, since if they're being calculated based on actual latitude/longitude, they should be fixed!

https://publiclab.github.io/leaflet-blurred-location/examples/

**Comment by jywarren** [comment]
OK - i set it up at https://github.com/publiclab/leaflet-blurred-location/issues/36

**Pull request merged**
