### PR TITLE
Change input to button

### PR DESCRIPTION
**Pull request by amitsin6h**
Input with 'Get my location' in demo is changed with button.

### CODE REVIEW

**Comment by jywarren** [comment]
Looks great! Can you attach a screenshot please? 👍

**Comment by amitsin6h** [comment]
screenshot from 2018-02-27 11-10-08


@jywarren hope that looks great.

**Comment by jywarren** [comment]
Fantastic work. It looks super!!! 👍 👍 💯

**Comment by jywarren** [comment]
We'd love your help with another issue if you're interested! :-)

**Comment by amitsin6h** [comment]
@jywarren It will be my pleasure to help Public Lab. You can count me for any issues to work.

**Pull request merged**
