### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by aliciapaz**
Try migration to GitHub Actions.

### CODE REVIEW

**Comment by aliciapaz** [comment]
For some reason, this is still trying to run the Travis checks

**Comment by aliciapaz** [comment]
@jywarren maybe Travis is required by the integration settings of the repository?

**Comment by jywarren** [comment]
Hooray! 

```
25 specs in 1.213s.
>> 0 failures
```

**Comment by jywarren** [comment]
Nicely done!!!!

**Pull request merged**
