### PR TITLE
Refactoring gridSystem.js

### PR DESCRIPTION
**Pull request by mridulnagpal**

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren started with refactoring, will keep on putting PRs for this

**Comment by jywarren** [comment]
This is looking good -- modularization and all! Is this PR ready, or are you going to add more? I recommend doing smaller PRs so we can see changes more granularly -- especially if something goes wrong!

Great work!

**Comment by mridulnagpal** [comment]
Awesome!! Shall we merge this in then?

**Comment by jywarren** [comment]
Done! Does this include the changes from https://github.com/publiclab/leaflet-blurred-location/pull/129 ?

**Pull request merged**
