### PR TITLE
Code separation Geocoding.js

### PR DESCRIPTION
**Pull request by mridulnagpal**
Added just one method, will add all others as well. Please send in a list of all preferred methods to be in Geocoding.js

### CODE REVIEW

**Comment by jywarren** [comment]
Great!!!! :-)

What do you think about `panMapByBrowserGeocode`?

https://github.com/publiclab/leaflet-blurred-location/pull/124/files#diff-8914aa74753366419a4ebf41e78f06f3L143

**Comment by mridulnagpal** [comment]
@jywarren Done with panMapByBrowserGeocode, whats next?

**Comment by jywarren** [comment]
Shall we go ahead and merge this in and do it in stages? It's great just to have the framework in place to move things over!

**Comment by mridulnagpal** [comment]
@jywarren  Awesome!! Merging let me know what all methods to separate after this

**Comment by jywarren** [comment]
OK -- let's remove the commented out code from `blurredLocation.js`, and move 
`  function panMapToGeocodedLocation(selector) {` and `  function geocodeWithBrowser(boolean) {
`  into `Geocoding.js`? 

How does that sound?

**Pull request merged**
