### PR TITLE
Bugs Fixed

### PR DESCRIPTION
**Pull request by mridulnagpal**
-> Miscalculation of boxes
-> Get my location bug
-> Precision -1 out of range
-> Timeout for get my location 
-> Pan map to text location

### CODE REVIEW

**Comment by jywarren** [comment]
This is looking good -- do you think it's ready for review and merging? Thanks!!

**Comment by jywarren** [comment]
This looks good - however, i still get this error when i enter a location, then pan around a lot, then enter a new location and press Enter:

```
Uncaught TypeError: Cannot read property 'geometry' of undefined
    at geocodeStringAndPan (Leaflet.BlurredLocation.js:889)
    at Leaflet.BlurredLocation.js:860
```

Then, I deleted a few letters and re-entered them to retrigger the geolocation, and then it worked. 

So more narrowly, I think that after searching for a new place like "Leuven, Belgium", then panning, then just pressing Enter on the same original string "Leuven, Belgium", it does not retrigger the centering, where it seems like it ought to. 

Maybe we need a new listener for Enter-pressing in the input form -- our current listener may only be listening for changes? We could try to detect additional enter-presses even if the string hasn't changed, and in that case, re-use the last already-loaded location... what do you think?

Thanks, @mridulnagpal -- this really is much smoother and more usable already!

**Comment by mridulnagpal** [comment]
@jywarren On it! :+1:

**Comment by jywarren** [comment]
Awesome, thanks Mridul!

**Comment by jywarren** [comment]
So here I think the last thing is to detect `enter` pressed in the geocoding form input, and re-trigger the geocode (even though the input value hasn't changed).

We'll have to watch to ensure it doesnt double-trigger if the input HAS changed AND enter is pressed.

A bonus would be to detect that it hasn't changed, and just use the last location we looked up (i.e. save it) but that's just an optimization.

**Comment by jywarren** [comment]
Just tell me when this one is ready, Mridul! Thanks!

**Comment by mridulnagpal** [comment]
Sorry, was out of town, On it right away!!

**Comment by jywarren** [comment]
want to generate a new release by bumping the package.json version and
making a new release at
https://github.com/publiclab/leaflet-blurred-location/releases ? i can
publish to npm once you do.

**Comment by mridulnagpal** [comment]
Sounds awesome, current version is 1.1.12, should the next version be 1.1.13 or 1.2.0 as we have done a lot of major changes

**Comment by jywarren** [comment]
Semver.org has some guidance -- if it's bugfixes, 0.0.x increase works, but
if we added new features, 0.x.0 -- we only change x.0.0 if we break an
existing API or interface and people using the library will have to
refactor. Make sense?

This looks great Mridul, i tested it and it's AWESOME!!!!! Great work!!

**Pull request merged**
