### PR TITLE
Add tile layer to options

### PR DESCRIPTION
**Pull request by cesswairimu**
Allow tile layer link to options to be used when initializing map as `options.tileLayerUrl`

### CODE REVIEW

**Comment by cesswairimu** [comment]
layers

**Comment by cesswairimu** [comment]
Done...Thanks @jywarren

**Comment by cesswairimu** [comment]
Could someone please merge this one for me...Thanks

**Comment by jywarren** [comment]
👍

**Comment by cesswairimu** [comment]
Thanks

**Comment by cesswairimu** [comment]
Happy new year @jywarren :wave: , could you please publish this version when you get a sec? Thanks

**Comment by jywarren** [comment]
Yes!! Happy new year to you too! 🎉 🍾

**Comment by jywarren** [comment]
Done!

**Comment by jywarren** [comment]
`v1.5.1`

**Comment by cesswairimu** [comment]
Great... Thanks a lot

**Pull request merged**
