### PR TITLE
got addGrid to run

### PR DESCRIPTION
**Pull request by jywarren**
Hi, @mridulnagpal! Check it out -- not such big changes, but I realize you were requiring in `addGrid` but not actually running it. I also changed some spacing and indentation (fixing part of #15) and unplugged the `getPlacenameFromCoordinates()` reference (used to have different name) from `addGrid.js`. 

I think we need to restructure `addGrid` to have submethods, so we can do (proposing a renaming too):

```js
gridSystem = require('./GridSystem.js');
gridSystem.setup(options.map);
gridSystem.disable(); // turns off the grid! Could also be .remove()
```

If we create this submodule called `GridSystem` whose purpose is only to draw a grid, we can test that it's doing so, and leave it at that -- we no longer have to deal with the complexity in there.

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren You're a lifesaver thanks alot :smile:

**Comment by jywarren** [comment]
Try it! It works.

**Comment by jywarren** [comment]
Want to merge this?

**Comment by mridulnagpal** [comment]
@jywarren Thanks, you're a lifesaver :smile:

**Pull request merged**
