### PR TITLE
Geocoding working now .

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Fixes #161 .

This PR also adds spinner when geocoding 😄 !

**Comment by sagarpreet-chadha** [comment]
The issue here is that **leaflet-spinner** has peer dependencies of **leaflet@0.7.3**  . 

Peer dependencies are not installed automatically after **npm 3** !

I have tried **npm i npm-install-peers** but this is not working .

Had faced same problem while integrating with mapknitter but there we use **Bower**  which has concept of **Resolutions** to install multiple versions of same package .

Finally tried installing 2 versions of leaflet : one using npm name and another using git url , which also is not working .

**Comment by jywarren** [comment]
Would you mind resolving conflicts? Thank you!!!

**Comment by sagarpreet-chadha** [comment]
@jywarren ...resolved conflicts 😄 !
Also you can release this to npm so that we can use it in plots2 . Thanks !

**Comment by jywarren** [comment]
Hmm, it's saying we are at version 1.2.4 already?

**Comment by jywarren** [comment]
I'll bump for 1.2.5

**Comment by jywarren** [comment]
oh no! Wrong library! Well, i bumped this too, no harm done since I did so without introducing new code 😛 Will be more careful!

**Comment by jywarren** [comment]
OK, done!

**Pull request merged**
