### PR TITLE
Create config.yml

### PR DESCRIPTION
**Pull request by faithngetich**
Issue [link](https://github.com/publiclab/plots2/issues/3681#issuecomment-429254015)

### CODE REVIEW

**Comment by Dhiraj240** [comment]
@jywarren Please look at it, it seems okay to me.Also can i use this project for Gsoc 2019 ? to prove my skills for this project what actually i should be doing.

**Comment by jywarren** [comment]
Retesting after a merge!

**Comment by Dhiraj240** [comment]
@jywarren is it not a right place to ask a question because i haven't got an answer for that ? I want to do a personal chat with you on gitter.Please check it.

**Comment by jywarren** [comment]
oh sorry Dhiraj - i don't always check Gitter. Can you email me at
jeff@publiclab.org? Thanks!

**Pull request merged**
