### PR TITLE
Set origin of the grid to (0,0)

### PR DESCRIPTION
**Pull request by mridulnagpal**
Test at https://mridulnagpal.github.io/leaflet-blurred-location/examples/

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren closes #36

**Comment by jywarren** [comment]
Whoa, the only file that's been changed here now is the `dist/Leaflet.BlurredLocation.js` -- be careful you haven't overwritten your changes!

**Comment by mridulnagpal** [comment]
Looking into it

**Comment by mridulnagpal** [comment]
Should work just fine now

**Comment by jywarren** [comment]
Ah, very cool, can you push it to the `gh-pages` branch again now so I can try it out?

**Comment by mridulnagpal** [comment]
Done , have a look

**Comment by jywarren** [comment]
Hmm, this still isn't working for me the way the Graticule plugin is. I think we gain a lot from using that plugin, for example, the edge of the map shows labels, and we can rely on that project's maintainers a bit for support rather than doing our own code. 

I'm going to merge this in, because the tests work and are great, but I'd like to request that you integrate the Graticule plugin for the grid work -- inside of the GridSystem class, so we'll still be customizing it a lot.

**Pull request merged**
