### PR TITLE
New module used for blurry metrics (km)

### PR DESCRIPTION
**Pull request by mridulnagpal**

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren Used this for metrics https://www.npmjs.com/package/haversine-distance

**Comment by mridulnagpal** [comment]
blurry-distance
@jywarren Here is a sample, also tests added

**Comment by jywarren** [comment]
Could we have it say "each grid square is roughly ____ wide" when you zoom?

Awesome! Let's get some documentation in this PR as well. Great work!

**Comment by mridulnagpal** [comment]
@jywarren I changed the text in the alert command, should we keep it in button format or change it to something else?

**Comment by jywarren** [comment]
I think it'd be really cool to have a text that updates whenever you zoom or pan, rather than clicking on a button - what do you think?

**Comment by jywarren** [comment]
Perfect!!!

**Comment by mridulnagpal** [comment]
Let's merge it then!!

**Comment by jywarren** [comment]
Super! Let's insert this into `plots2`'s implementation, no? And add some documentation on how to use it, like the `scaleDisplay` id?

**Pull request merged**
