### PR TITLE
lat lon when entered changes the map location

### PR DESCRIPTION
**Pull request by mridulnagpal**
solves #23

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@jywarren Please have a look will post separate PR's for separate issues from now on.

**Comment by jywarren** [comment]
Ok but why is some code commented out? It seems unrelated to the PR title?

**Comment by mridulnagpal** [comment]
@jywarren We have not added google as a property yet, thus it shows an error. As soon as we reach that part I will uncomment it so that it shows no errors

**Comment by jywarren** [comment]
Can you create an issue for that and then merge this?

**Comment by mridulnagpal** [comment]
@jywarren I think we have the google API we just need to uncomment the method

**Comment by mridulnagpal** [comment]
@jywarren No more conflicts

**Comment by mridulnagpal** [comment]
On it

**Comment by mridulnagpal** [comment]
@jywarren Done have a look

**Comment by jywarren** [comment]
Looks good, no? Go ahead and merge!

But we haven't tested the function the PR names -- I think for that we have to actually write a test that sets the value of the input and sends a "change" event, then tests if the map has changed. 

I'll make a new issue.

**Pull request merged**
