### PR TITLE
FIX: Auto-locate me button multiple spinners

### PR DESCRIPTION
**Pull request by VladimirMikulic**
[Demo](https://streamable.com/hl8yz)

On the demo, you can't see me clicking "Don't allow" on Firefox popup, my screen recorder doesn't capture them for some reason. You can see me moving the cursor from the button and clicking on "empty page", but it's actually Don't allow" button on the popup.

Resolves https://github.com/publiclab/plots2/issues/7305

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
Initially, an arrow function was the problem, but now when I fixed it tests are successful on localhost but they fail in Travis.

**Comment by VladimirMikulic** [comment]
@jywarren we can merge this :)

**Comment by VladimirMikulic** [comment]
@sagarpreet-chadha this is ready. Could you please review this? Thanks.

**Comment by VladimirMikulic** [comment]
@sagarpreet-chadha done :)

**Comment by sagarpreet-chadha** [comment]
Awesome thanks!!!

**Pull request merged**
